apiVersion: v1
data:
  proxy-set-headers: {{ .Values.service.namespace }}/{{ .Values.service.name }}-custom-headers
kind: ConfigMap
metadata:
  name: {{ .Values.service.name }}-config
  namespace: {{ .Values.service.namespace }}
