{{- if eq .Values.nginx_lb.enabled "true"}}
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.service.name }}"
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "{{ .Values.service.ssl.aws_certificate_arn }}"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "{{ .Values.elb.tags }}"
spec:
  type: LoadBalancer
  ports:
    # Removed the plaintext port - but we could reinstate with an https redirect in future.
    # - port: 80
    #  name: http
    - port: 443
      name: https
      targetPort: 80
      protocol: TCP
  selector:
    k8s-app: "{{ .Values.service.name }}-load-balancer"
{{- end }}
